version: '3.9'
services:
  api:
    image: python:3.11-slim
    working_dir: /code
    command: uvicorn blackletter_api.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - ./apps/api:/code
      - api_data:/data
    ports:
      - "8000:8000"
  web:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "pnpm install && pnpm dev"
    env_file:
      - .env
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
    ports:
      - "3000:3000"
volumes:
  api_data:
  web_node_modules:
