markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: 01 -John @ blackletter_PRD.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding_standards.md
  - docs/architecture/tech_stack.md
  - docs/architecture/source_tree.md
  - .bmad-core/core-config.yaml
  - apps/api/blackletter_api/rules/art28_v1.yaml
  - apps/api/blackletter_api/rules/lexicons/weak_language.yaml
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
