name: Auto-merge Low-Risk Jules PRs
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
permissions:
  contents: write
  pull-requests: write
jobs:
  merge:
    if: >
      github.event.pull_request.user.login == 'jules[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'low-risk') &&
      !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const { data: statuses } = await github.rest.repos.getCombinedStatusForRef({
              owner: context.repo.owner, repo: context.repo.repo, ref: pr.head.sha
            });
            if (statuses.state !== 'success') return;
            await github.rest.pulls.merge({
              owner: context.repo.owner, repo: context.repo.repo,
              pull_number: pr.number, merge_method: "squash"
            });
