name: build-and-push
on:
  workflow_dispatch:
  push:
    paths:
      - blackletter/blackletter-upstream/**/Dockerfile
      - blackletter/blackletter-upstream/**/*
      - deploy/docker/Dockerfile
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            dockerfile: blackletter/blackletter-upstream/src/backend/Dockerfile
            context:   blackletter/blackletter-upstream/src/backend
            image:     blackletter/backend
          - name: frontend
            dockerfile: blackletter/blackletter-upstream/frontend/Dockerfile
            context:   blackletter/blackletter-upstream/frontend
            image:     blackletter/frontend
    steps:
      - uses: actions/checkout@v4
      - name: Docker login to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login "${{ secrets.ACR_LOGIN_SERVER }}" \
             -u "${{ secrets.ACR_USERNAME }}" --password-stdin
      - name: Build and push ${{ matrix.name }}
        run: |
          TAG=${GITHUB_SHA::7}
          IMAGE="${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:${TAG}"
          docker build -t "$IMAGE" -f "${{ matrix.dockerfile }}" "${{ matrix.context }}"
          docker push "$IMAGE"
          echo "pushed=$IMAGE" >> $GITHUB_OUTPUT
