name: Automation Tests (non-blocking)
on:
  push:
    paths: ["automation/**", "package.json", "vitest.config.mjs"]
  pull_request:
    paths: ["automation/**", "package.json", "vitest.config.mjs"]
permissions:
  contents: read
jobs:
  node-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm test
