name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    name: "Backend CI (API & Workers)"
    defaults:
      run:
        working-directory: ./apps/api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Placeholder for requirements file

      - name: Lint with Ruff
        run: pip install ruff && ruff check .

      - name: Test with pytest
        run: pip install pytest && pytest

  frontend-ci:
    runs-on: ubuntu-latest
    name: "Frontend CI (Web)"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install root dependencies
        run: pnpm install

      - name: Build and test frontend
        working-directory: ./apps/web
        run: |
          pnpm lint
          pnpm test -- --run
          pnpm e2e:install
          pnpm test:e2e
          NEXT_DISABLE_ESLINT=1 pnpm build
          pnpm typecheck
