name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    name: "Backend CI (API & Workers)"
    defaults:
      run:
        working-directory: ./apps/api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Placeholder for requirements file

      - name: Lint with Ruff
        run: pip install ruff && ruff check .

      - name: Test with pytest
        run: pip install pytest && pytest

  frontend-ci:
    runs-on: ubuntu-latest
    name: "Frontend CI (Web)"
    defaults:
      run:
        working-directory: ./apps/web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js with pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'apps/web/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm -w install
      - name: Lint
        run: pnpm lint
      - name: Format
        run: pnpm -w format

      - name: Unit tests
        run: pnpm test -- --run

      - name: Install Playwright browsers
        run: pnpm e2e:install

      - name: E2E tests
        run: pnpm test:e2e

      - name: Build project
        run: NEXT_DISABLE_ESLINT=1 pnpm build

      - name: Type-check with TypeScript
        run: pnpm typecheck
