name: CI (API tests)

on: [push, pull_request]

concurrency:
  group: main-ci
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r apps/api/requirements.txt
      - run: npm ci || true
      - run: npm test
