name: Codex • Issue to task
on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]
jobs:
  plan-or-fix:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'codex:run')) ||
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/codex'))
    steps:
      - uses: actions/checkout@v4
      - name: Create work branch
        id: create_branch
        uses: actions/github-script@v7
        with:
          script: |
            const base = (await github.rest.repos.get({owner: context.repo.owner, repo: context.repo.repo})).data.default_branch;
            const issue = context.payload.issue || (await github.rest.issues.get({owner:context.repo.owner, repo:context.repo.repo, issue_number: context.payload.issue.number})).data;
            const feature = issue.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,60);
            const ref = `codex/${feature}`;
            const sha = (await github.rest.repos.getBranch({owner: context.repo.owner, repo: context.repo.repo, branch: base})).data.commit.sha;
            try { await github.rest.git.createRef({owner: context.repo.owner, repo: context.repo.repo, ref: `refs/heads/${ref}`, sha}); } catch(e){}
            core.setOutput('branch', ref);
      - name: Open scaffold PR & summon @codex
        uses: actions/github-script@v7
        with:
          script: |
            const title = `[Plan] ${context.payload.issue.title}`;
            const head = `${{ steps.create_branch.outputs.branch || '' }}` || 'codex/tmp';
            const pr = await github.rest.pulls.create({owner:context.repo.owner, repo:context.repo.repo, title, head, base: (await github.rest.repos.get({owner:context.repo.owner, repo:context.repo.repo})).data.default_branch, body: 'Auto-created from issue.\n\n@codex Please propose plan, tasks and initial diff.'});
            await github.rest.issues.createComment({owner:context.repo.owner, repo:context.repo.repo, issue_number: pr.data.number, body: '@codex\n\nKick off planning with the **codegen** profile.'});
