name: Codex • Nightly upkeep
on:
  schedule: [{ cron: "12 2 * * *" }]  # daily 02:12 UTC
  workflow_dispatch:
jobs:
  upkeep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quick health (backend)
        run: |
          python -m pip install -r apps/api/requirements.txt || true
          pytest -q apps/api || true
      - name: Quick health (frontend)
        run: |
          corepack enable || true
          pnpm -C apps/web install --frozen-lockfile || true
          pnpm -C apps/web -r lint || true
          pnpm -C apps/web -r build || true
      - name: Ping @codex with status
        uses: actions/github-script@v7
        with:
          script: |
            const body = "@codex\n\nNightly upkeep complete. Summarize failures and propose patches if any.";
            await github.rest.issues.create({owner:context.repo.owner, repo:context.repo.repo, title:"Nightly report", body});
