name: Deploy to Azure Container Apps (DISABLED)

# Disabled - Using Azure Static Web Apps instead
# To re-enable, uncomment the 'on' section below and set up Azure service principal secrets

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

env:
  REGISTRY: blackletteracr.azurecr.io
  IMAGE_NAME: blackletter

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Log in to Azure Container Registry
      run: az acr login --name blackletteracr

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./deploy/docker/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: blackletteracr
        containerAppName: blackletter-web
        resourceGroup: blackletter-rg
        imageToBuild: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy API to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: blackletteracr
        containerAppName: blackletter-api
        resourceGroup: blackletter-rg
        imageToBuild: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
