name: Jules Plan Autopilot
on:
  issues:
    types: [opened, labeled, edited]
permissions:
  issues: write
jobs:
  approve:
    if: contains(github.event.issue.labels.*.name, 'jules')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const number = context.payload.issue.number;

            // cooldown so Jules can post the plan first
            await new Promise(r => setTimeout(r, 90000));

            // Skip if we've already approved
            const comments = await github.paginate(github.rest.issues.listComments, {
              owner, repo, issue_number: number, per_page: 100
            });
            const already = comments.some(c =>
              /Approved by policy\. Proceed/i.test(c.body || '')
            );
            if (already) return;

            await github.rest.issues.createComment({
              owner, repo, issue_number: number,
              body: "Approved by policy. Proceed ✅"
            });
