name: VibeCEO — Issues
on:
  issues:
    types: [opened, labeled, edited]
permissions:
  issues: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci || npm i
      - uses: actions/github-script@v7
        with:
          script: |
            const runner = require('./automation/vibeceo/index.js');
            await runner({ github, context, core });
