name: VibeCEO — PRs (DISABLED - BYPASSED)
on:
  workflow_dispatch:  # Disabled automatic triggers
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  run:
    runs-on: ubuntu-latest
    if: false  # Always skip this job
    steps:
      - name: VibeCEO Disabled
        run: echo "VibeCEO is disabled due to configuration issues. Auto-merge relies on CI + Jules workflow only."
