name: web-swa
on: { push: { branches: [main] }, workflow_dispatch: {} }
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '18.x', cache: 'pnpm', cache-dependency-path: 'pnpm-lock.yaml' }
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright/
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      - run: pnpm --filter ./apps/web run e2e:install
      - run: pnpm --filter ./apps/web run test:e2e
      - run: pnpm --filter ./apps/web build
      - uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_TOKEN }}
          app_location: apps/web
          output_location: out
